### ISSUE TITLE
Does this support multiple apps on different ports on the same host?

### ISSUE THREAD

**Issue by pentatronix** [donasaur/http-proxy-rules#7]
I'm trying to create the reverse proxy with multiple apps on various ports pointed at different paths.  Unfortunately every time I try to connect I get connection refused.  Is this possible?

```javascript
  var HttpProxyRules, cb, http, httpProxy, proxy, proxyRules;

  http = require('http');

  httpProxy = require('http-proxy');

  HttpProxyRules = require('http-proxy-rules');

  cb = function(value1, value2) {
    return console.log(value1, value2);
  };

  proxyRules = new HttpProxyRules({
    "default": 'http://localhost:6000',
    rules: {
      '.*/': 'http://localhost:6000',
      '.*/otherapp': 'http://localhost:3000/oauthv2/'
    }
  });

  proxy = httpProxy.createProxy();

  http.createServer(function(req, res) {
    var target;
    target = proxyRules.match(req);
    if (target) {
      return proxy.web(req, res, {
        target: target
      });
    }
    res.writeHead(500, {
      'Content-Type': 'text/plain'
    });
    return res.end('The request url and path did not match any of the listed rules!');
  }).listen(5000, cb); 
```

And the result when I hit that port (The other app is up and listening on 6000):

```
Error: connect ECONNREFUSED 127.0.0.1:6000
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

```

**Comment by donasaur** [comment]
Isn't the other app in your example running on port 3000?

This module should support multiple apps running on different ports of the same host.
